### ISSUE TITLE
[FEATURE REQUEST] Gears of War 2-3-Judgement support

### ISSUE THREAD

**Issue by ZidaneTri** [marinesciencedude/xenia-canary-mousehook#19]
### Describe what's going wrong

Basically the title, it would be nice to have 360-exclusive GoW games with proper controls.

### Describe what should happen

Every GoW fan will be happy to have at least some resemblance of port which Microsoft should have done a long time ago.

**Comment by Clippy95** [comment]
If you're still interested I _believe_ I got working now
https://github.com/marinesciencedude/xenia-canary-mousehook/pull/27

**Comment by ZidaneTri** [comment]
> If you're still interested I _believe_ I got working now #27

I was ready to wait a few years more, so yes, I'm still interested and will test it as soon as new release is available.
Thanks for doing this!

**Comment by Clippy95** [comment]
> > If you're still interested I _believe_ I got working now #27
> 
> I was ready to wait a few years more, so yes, I'm still interested and will test it as soon as new release is available. Thanks for doing this!

You can get it from [Actions](https://github.com/marinesciencedude/xenia-canary-mousehook/actions/runs/10656469672) If you have Judgement I need someone to see if it works there, have had other people test the other games except Judgment, it should work fine but I'd like to double check

**Comment by ZidaneTri** [comment]
> If you have Judgement I need someone to see if it works there

I am, works flawlessly and special fix in settings is seems to do its job. 
I also tested 2 and 3. In 2 I had no problems, however with 3 there is a problem with TU0 - X-axis movement is fine, but on Y-axis movement are inverted, very jagged and half of the time the reticle shifts along two axes at once. Special fix on/off has no effect on this, but if invert Y-axis in settings, jagginess is gone (but it still inverted, as should be). After updating to TU4 problem is gone.

**Comment by Clippy95** [comment]
> > If you have Judgement I need someone to see if it works there
> 
>  X-axis movement is fine, but on Y-axis movement are inverted, very jagged and half of the time the reticle shifts along two axes at once. Special fix on/off has no effect on this, but if invert Y-axis in settings, jagginess is gone (but it still inverted, as should be). After updating to TU4 problem is gone.

Could you show me a video? I don't have this issue,
what you're describing is what happened when I had the right stick workaround implemented without slowing the in-game camera down, but it's weird that it's still happening to you with it off

**Comment by ZidaneTri** [comment]
> Could you show me a video?

Sure, https://www.youtube.com/watch?v=QJWWzprzH_I
I also tested a newer build, it improved things a bit, but still the same problem and again there is no problem after TU.

**Comment by Clippy95** [comment]
> > Could you show me a video?
> 
> Sure, https://www.youtube.com/watch?v=QJWWzprzH_I I also tested a newer build, it improved things a bit, but still the same problem and again there is no problem after TU.

Yeah this is exactly how it was when I first implemented right stick workaround, are you in the Xenia Canary discord, there's a mousehook thread in #media-only I need more info and have more questions cause this is weird it's supposed to not happen  when it's turned off in the config too..
